/*
 * This source file was generated by the Gradle 'init' task
 */
package com.blocklollo.gateway

class MessageUtils {
    companion object {
        fun getMessage(): String = "Hello      World!"
    }
}
